### ISSUE TITLE
Playing life

### ISSUE THREAD

**Issue by pmx625** [nedhyett/Life#1]
Hey I'm known as }SGC-S{ [Pres.] Majo Lorne(Pmx) IN steam (the guy that gives you some ideas for vermilion developement). I wanted to know If this gamemode can be played at the moment and if I can use it on my Garry's Mod Server. Also I wanted to know if it is playable In some other maps like sg1_the_fifth_race and with mods (like pointshop, carter addon pack, etc).
Also I didnt know where I should post this so if it is in the wrong place just let me know so I can move it to the correct one. 
Links you will probably need:
Carter Addon Pack (CAP): http://sg-carterpack.com
Sg1_the_fifth_race: http://steamcommunity.com/sharedfiles/filedetails/?id=104753884
Pointshop: http://pointshop.burt0n.net

**Comment by nedhyett** [comment]
Wrong project. This is a Java game I wrote. This has nothing to do with GMod. I don't know about this gamemode, since I haven't played it myself and I don't have the time available to test everything.
